/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/basket/edit/[id]': RouteRecordInfo<'/basket/edit/[id]', '/basket/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/basket/exemple/[data]': RouteRecordInfo<'/basket/exemple/[data]', '/basket/exemple/:data', { data: ParamValue<true> }, { data: ParamValue<false> }>,
    '/basket/new': RouteRecordInfo<'/basket/new', '/basket/new', Record<never, never>, Record<never, never>>,
    '/Form': RouteRecordInfo<'/Form', '/Form', Record<never, never>, Record<never, never>>,
    '/formulaire1': RouteRecordInfo<'/formulaire1', '/formulaire1', Record<never, never>, Record<never, never>>,
    '/formulaire2': RouteRecordInfo<'/formulaire2', '/formulaire2', Record<never, never>, Record<never, never>>,
  }
}
